[package]
name = "mews-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
mews-agent = { path = "../mews-agent" }
mews-protocol = { path = "../mews-protocol" }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
