[package]
name = "mews-channel"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
fs2.workspace = true
futures-util.workspace = true
mews-client = { path = "../mews-client" }
mews-protocol = { path = "../mews-protocol" }
rusqlite.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
